import { db } from '@/db';
import { automationActions } from '@/db/schema';

async function main() {
    const sampleAutomationActions = [
        // AUTOMATION 1 - "Living Room Evening Lights" Actions
        {
            automationId: 1,
            type: 'service_call',
            service: 'light.turn_on',
            entityId: 'light.living_room',
            data: { brightness: 180, color_temp: 370 },
            topic: null,
            payload: null,
            sceneId: null,
            createdAt: new Date('2024-01-15T09:15:00Z').toISOString(),
            updatedAt: new Date('2024-01-15T09:15:00Z').toISOString(),
        },
        {
            automationId: 1,
            type: 'service_call',
            service: 'light.turn_on',
            entityId: 'light.living_room_lamp',
            data: { brightness: 120 },
            topic: null,
            payload: null,
            sceneId: null,
            createdAt: new Date('2024-01-15T09:16:00Z').toISOString(),
            updatedAt: new Date('2024-01-15T09:16:00Z').toISOString(),
        },
        {
            automationId: 1,
            type: 'scene',
            service: null,
            entityId: null,
            data: null,
            topic: null,
            payload: null,
            sceneId: 'scene.evening_ambiance',
            createdAt: new Date('2024-01-15T09:17:00Z').toISOString(),
            updatedAt: new Date('2024-01-15T09:17:00Z').toISOString(),
        },

        // AUTOMATION 2 - "Motion Security Alert" Actions
        {
            automationId: 2,
            type: 'service_call',
            service: 'light.turn_on',
            entityId: 'light.security_front',
            data: { brightness: 255, color_name: 'red' },
            topic: null,
            payload: null,
            sceneId: null,
            createdAt: new Date('2024-01-16T10:30:00Z').toISOString(),
            updatedAt: new Date('2024-02-10T14:20:00Z').toISOString(),
        },
        {
            automationId: 2,
            type: 'service_call',
            service: 'notify.mobile_app',
            entityId: 'notify.phone_john',
            data: { message: 'Motion detected at front door!', title: 'Security Alert' },
            topic: null,
            payload: null,
            sceneId: null,
            createdAt: new Date('2024-01-16T10:31:00Z').toISOString(),
            updatedAt: new Date('2024-02-10T14:20:00Z').toISOString(),
        },
        {
            automationId: 2,
            type: 'mqtt',
            service: null,
            entityId: null,
            data: null,
            topic: 'home/security/alert',
            payload: '{"type": "motion", "location": "front_door", "timestamp": "now"}',
            sceneId: null,
            createdAt: new Date('2024-01-16T10:32:00Z').toISOString(),
            updatedAt: new Date('2024-01-16T10:32:00Z').toISOString(),
        },
        {
            automationId: 2,
            type: 'service_call',
            service: 'camera.snapshot',
            entityId: 'camera.front_door',
            data: { filename: '/config/www/snapshots/motion_{{ now().strftime(\'%Y%m%d_%H%M%S\') }}.jpg' },
            topic: null,
            payload: null,
            sceneId: null,
            createdAt: new Date('2024-01-16T10:33:00Z').toISOString(),
            updatedAt: new Date('2024-01-16T10:33:00Z').toISOString(),
        },

        // AUTOMATION 3 - "Morning Routine" Actions
        {
            automationId: 3,
            type: 'service_call',
            service: 'light.turn_on',
            entityId: 'light.bedroom',
            data: { brightness: 50, transition: 300 },
            topic: null,
            payload: null,
            sceneId: null,
            createdAt: new Date('2024-01-18T07:00:00Z').toISOString(),
            updatedAt: new Date('2024-02-05T08:15:00Z').toISOString(),
        },
        {
            automationId: 3,
            type: 'service_call',
            service: 'switch.turn_on',
            entityId: 'switch.coffee_maker',
            data: {},
            topic: null,
            payload: null,
            sceneId: null,
            createdAt: new Date('2024-01-18T07:01:00Z').toISOString(),
            updatedAt: new Date('2024-01-18T07:01:00Z').toISOString(),
        },
        {
            automationId: 3,
            type: 'service_call',
            service: 'light.turn_on',
            entityId: 'light.kitchen',
            data: { brightness: 200, transition: 180 },
            topic: null,
            payload: null,
            sceneId: null,
            createdAt: new Date('2024-01-18T07:02:00Z').toISOString(),
            updatedAt: new Date('2024-02-05T08:15:00Z').toISOString(),
        },
        {
            automationId: 3,
            type: 'service_call',
            service: 'media_player.play_media',
            entityId: 'media_player.bedroom_speaker',
            data: { media_content_id: 'playlist:morning_news', media_content_type: 'playlist' },
            topic: null,
            payload: null,
            sceneId: null,
            createdAt: new Date('2024-01-18T07:03:00Z').toISOString(),
            updatedAt: new Date('2024-01-18T07:03:00Z').toISOString(),
        },

        // AUTOMATION 4 - "Away Mode" Actions
        {
            automationId: 4,
            type: 'service_call',
            service: 'light.toggle',
            entityId: 'light.living_room',
            data: {},
            topic: null,
            payload: null,
            sceneId: null,
            createdAt: new Date('2024-01-20T11:45:00Z').toISOString(),
            updatedAt: new Date('2024-02-12T16:30:00Z').toISOString(),
        },
        {
            automationId: 4,
            type: 'service_call',
            service: 'light.toggle',
            entityId: 'light.kitchen',
            data: {},
            topic: null,
            payload: null,
            sceneId: null,
            createdAt: new Date('2024-01-20T11:46:00Z').toISOString(),
            updatedAt: new Date('2024-02-12T16:30:00Z').toISOString(),
        },
        {
            automationId: 4,
            type: 'local_device',
            service: null,
            entityId: 'light.bedroom',
            data: { action: 'random_toggle', min_delay: 300, max_delay: 1800 },
            topic: null,
            payload: null,
            sceneId: null,
            createdAt: new Date('2024-01-20T11:47:00Z').toISOString(),
            updatedAt: new Date('2024-01-20T11:47:00Z').toISOString(),
        },
        {
            automationId: 4,
            type: 'mqtt',
            service: null,
            entityId: null,
            data: null,
            topic: 'home/presence/simulation',
            payload: '{"mode": "away", "action": "light_toggle", "random": true}',
            sceneId: null,
            createdAt: new Date('2024-01-20T11:48:00Z').toISOString(),
            updatedAt: new Date('2024-01-20T11:48:00Z').toISOString(),
        },
        {
            automationId: 4,
            type: 'service_call',
            service: 'script.random_light_pattern',
            entityId: 'script.away_mode_lights',
            data: { duration: 3600 },
            topic: null,
            payload: null,
            sceneId: null,
            createdAt: new Date('2024-01-20T11:49:00Z').toISOString(),
            updatedAt: new Date('2024-01-20T11:49:00Z').toISOString(),
        },
    ];

    await db.insert(automationActions).values(sampleAutomationActions);
    
    console.log('✅ Automation actions seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});